name: build & deploy
on:
  workflow_dispatch:

# Required for GitHub OIDC authentication with AWS
permissions:
  contents: read
  id-token: write

# ============================================================
# STAGE 1 - BUILD AND TEST
# ============================================================
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Java 21 and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Verify Java version
        run: java -version

      - name: Verify Maven version
        run: mvn -version

      - name: Run tests
        run: mvn clean test

      - name: Build application
        run: mvn clean package

      - name: verify jar file
        run: | # ls -l target/*.jar
          ls -lh target/
          test -f target/streamflix-1.0.0.jar

      - name: Prepare Elastic Beanstalk package
        run: |
          mkdir eb-deployment
          cp target/*.jar eb-deployment/
          echo "web: java -jar *.jar" > eb-deployment/Procfile
      
      - name: upload application artifact
        uses: actions/upload-artifact@v3
        with:
          name: streamflix-deployment
          path: eb-deployment/